NUMPY


In [1]:
import numpy as np


In [2]:
!ls


sample_data  student_data.csv


In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('/content/student_data.csv')

In [5]:
df.head()

Unnamed: 0  Gender EthnicGroup          ParentEduc     LunchType TestPrep  \
0           1  female     group C        some college      standard      NaN   
1           2  female     group B     master's degree      standard     none   
2           3    male     group A  associate's degree  free/reduced     none   
3           4    male     group C        some college      standard     none   
4           5  female     group B  associate's degree      standard     none   

  ParentMaritalStatus PracticeSport IsFirstChild  NrSiblings TransportMeans  \
0             married     sometimes          yes         0.0            NaN   
1              single     sometimes          yes         4.0     school_bus   
2             married         never           no         1.0            NaN   
3             married     sometimes          yes         0.0     school_bus   
4             married     regularly          yes         1.0     school_bus   

  WklyStudyHours  MathScore  ReadingScore  WritingScore  
0         05-Oct         69            90            88  
1            < 5         87            93            91  
2         05-Oct         45            56            42  
3         05-Oct         76            78            75  
4         05-Oct         73            84            79

What is difference between list and numpy

as list is use for storing may or may not be different types and doing numerical operation for large data will take much time

but in numpy array is use for same datatypes and used for numerical operation of large data set and can be more than one rows and columns just like matrices and supports many linear algebric operations

In [9]:
from time import process_time


num_list = [i for i in range(10000)]
start_time = process_time()

num_list = [i+5 for i in num_list]
end_time = process_time()

total_time = end_time - start_time
print(total_time)

0.0009951279999995677


In [12]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array = np_array+5
end_time = process_time()
print(end_time - start_time)

0.00018422000000128946


In [13]:
np_array = np.array([i for i in range(10)])
type(np_array)
print(type(np_array))
print(np_array)

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [14]:
np_array = np.array([i for i in range(1,10)])
type(np_array)
print(type(np_array))
print(np_array)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


In [20]:
np_array.shape


(9,)

In [16]:
# crating multidimensional array

In [21]:
a = np.array([1,2,3,4])
a.shape


(4,)

In [22]:
print(a)

[1 2 3 4]


In [25]:
b = np.array([(1,2,3),(2,3,4),(3,4,5)])
b.shape

(3, 3)

In [28]:
print(a)
print(b)


[1 2 3 4]
[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [29]:
type(b)

numpy.ndarray

In [31]:
c = np.array([(1,2,3),(2,3,4),(2,3,3),(3,3,3)],dtype = float)
print(c)

[[1. 2. 3.]
 [2. 3. 4.]
 [2. 3. 3.]
 [3. 3. 3.]]


In [32]:
type(c)

numpy.ndarray

inital placeholder in numpy arrays

In [34]:
#create numpy array containing all the values is 0

x = np.zeros((1))
print(x)
y = np.zeros((2,3))

[0.]


In [35]:
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]


In [36]:
ones = np.ones((2,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [37]:
twos = np.twos((3,3))
print(twos)

AttributeError: module 'numpy' has no attribute 'twos'

In [38]:
#creating numpy array for particular value
particular_value = np.full((2,4),5)
print(particular_value)

[[5 5 5 5]
 [5 5 5 5]]


In [40]:
#creating indentity matrix or numpy array

iden = np.eye(4)
print(iden)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [45]:
#creating numpy array of random value

random_numpy =  np.random.random((2,3))
print(random_numpy)

[[0.0763791  0.18312534 0.39699224]
 [0.84820121 0.9886138  0.56862277]]


In [72]:
# creating numpy array for random value for integer in a defined range
random_int = np.random.randint(low=2,high=8,size=(3,5))
print(random_int)

[[3 7 3 4 5]
 [7 6 2 7 7]
 [2 3 4 6 5]]


In [58]:
# array of evenly spaced values by giving the argument starting,ending,and no of values you want

evenly_spaced = np.linspace(10,30,6)
print(evenly_spaced)

[10. 14. 18. 22. 26. 30.]


In [64]:
# for integer value

evenly_spaced2 = np.linspace(10,30,6,dtype=int)
print(evenly_spaced2)

[10 14 18 22 26 30]


In [67]:

evenly_spaced3 = np.linspace(10,30,22,dtype=int)
print(evenly_spaced3)

[10 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [66]:
evenly_spaced4 = np.linspace(10,30,22)
print(evenly_spaced4)

[10.         10.95238095 11.9047619  12.85714286 13.80952381 14.76190476
 15.71428571 16.66666667 17.61904762 18.57142857 19.52380952 20.47619048
 21.42857143 22.38095238 23.33333333 24.28571429 25.23809524 26.19047619
 27.14285714 28.0952381  29.04761905 30.        ]


In [69]:
# array of evenly spaced value -> specifying the step
step_array = np.arange(3,40,8)
print(step_array)

[ 3 11 19 27 35]


In [71]:
#convert a list to an numpy array

list1 = [2,2,3,4]
print(list1)
print(type(list1))
conv_to_numpy_array = np.asarray(list1)
print(conv_to_numpy_array)
print(type(conv_to_numpy_array))

[2, 2, 3, 4]
<class 'list'>
[2 2 3 4]
<class 'numpy.ndarray'>


Analysing a numpy array

In [73]:
np_arr = np.random.randint(3,9,size=(5,5))
print(np_arr)

[[6 7 6 6 5]
 [5 3 7 6 4]
 [7 3 8 3 4]
 [5 4 4 6 6]
 [3 7 6 4 3]]


In [76]:
#array dimensions
print(np_arr.shape)

(5, 5)


In [77]:
# number of dimensions
print(np_arr.ndim)

2


In [79]:
# no of element in an array
print(np_arr.size)

25


In [80]:
#checking the datatype of values of array
print(np_arr.dtype)

int64


Mathematical Operation on NumpyArray


In [81]:
list_1 = [2,3,4]
list_2 = [2,3,5]
print(list_1+list_2)

[2, 3, 4, 2, 3, 5]


In [82]:
list_1 = [2,3,4]
list_2 = [2,3,5,3,4,3]
print(list_1+list_2)
# plus sign help in concatenation

[2, 3, 4, 2, 3, 5, 3, 4, 3]


In [85]:
np_a = np.random.randint(0,4,size=(2,3))
np_b = np.random.randint(3,6,size=(2,3))
print(np_a)
print(np_b)
print(np_a + np_b)
# adding of corresponding values

[[2 3 0]
 [3 3 0]]
[[5 5 4]
 [5 3 3]]
[[7 8 4]
 [8 6 3]]


In [86]:
np_a = np.random.randint(0,4,size=(2,3))
np_b = np.random.randint(3,6,size=(2,3))
print(np_a)
print(np_b)
print(np_b + np_a)
# subtracting of corresponding values

[[2 0 1]
 [3 2 0]]
[[5 3 4]
 [4 5 5]]
[[7 3 5]
 [7 7 5]]


In [87]:
np_a = np.random.randint(0,4,size=(2,3))
np_b = np.random.randint(3,6,size=(2,3))
print(np_a)
print(np_b)
print(np_b * np_a)
# multiplication of corresponding values

[[1 3 3]
 [1 2 3]]
[[4 3 4]
 [3 3 5]]
[[ 4  9 12]
 [ 3  6 15]]


In [89]:
np_a = np.random.randint(1,4,size=(2,3))
np_b = np.random.randint(3,6,size=(2,3))
print(np_a)
print(np_b)
print(np_b / np_a)
# division of corresponding values

[[3 3 1]
 [2 1 2]]
[[3 5 5]
 [3 3 4]]
[[1.         1.66666667 5.        ]
 [1.5        3.         2.        ]]


In [92]:
print(np_a)
print(np_b)
print(np.add(np_a,np_b))
print(np.subtract(np_a,np_b))
print(np.multiply(np_a,np_b))
print(np.divide(np_a,np_b))

[[3 3 1]
 [2 1 2]]
[[3 5 5]
 [3 3 4]]
[[6 8 6]
 [5 4 6]]
[[ 0 -2 -4]
 [-1 -2 -2]]
[[ 9 15  5]
 [ 6  3  8]]
[[1.         0.6        0.2       ]
 [0.66666667 0.33333333 0.5       ]]


Array Manipulation

In [94]:
arr = np.random.randint(0,10,(2,3))
print(arr)
print(arr.shape)

[[7 5 3]
 [4 4 9]]
(2, 3)


In [98]:
#creating transpose of numpy array

trans = np.transpose(arr)
print(trans)
print(trans.shape)

[[7 4]
 [5 4]
 [3 9]]
(3, 2)


In [99]:
trans2 = arr.T
print(trans2)
print(trans2.shape)

[[7 4]
 [5 4]
 [3 9]]
(3, 2)


In [103]:
# reshaping the array

org_arr = np.random.randint(0,10,(2,3))
print(org_arr)
print(org_arr.shape)

reshape_arr = org_arr.reshape(3,2)
print(reshape_arr)
print(reshape_arr.shape)

# reshape_arr2 = org_arr.reshape(3,3)
# print(reshape_arr2)
# print(reshape_arr2.shape)





[[2 6 8]
 [5 7 1]]
(2, 3)
[[2 6]
 [8 5]
 [7 1]]
(3, 2)
