In [1]:
import numpy as np
import pandas as pd


Creating Matrix using numpy

In [2]:
matrix_1 = np.array([[2,3,4],[3,3,2]])

In [3]:
print(matrix_1)

[[2 3 4]
 [3 3 2]]


In [4]:
matrix_1.shape

(2, 3)

Creating Matrix with random values

In [5]:
random_matrix = np.random.rand(3,3)

In [6]:
print(random_matrix)

[[0.30517285 0.27607603 0.17114367]
 [0.17799741 0.57370052 0.47447304]
 [0.77835806 0.94232455 0.83507433]]


In [7]:
random_matrix.shape

(3, 3)

Creating  matrix with random integers

In [8]:
random_matrix2 = np.random.randint(100,size=(3,5))

In [9]:
print(random_matrix2)

[[17 50 11 79  9]
 [95 21 22 94 97]
 [64  5 16 90 97]]


In [10]:
random_matrix3 = np.random.randint(4,size=(10,10))

In [11]:
print(random_matrix3)

[[3 1 2 0 3 0 3 2 2 3]
 [0 0 2 2 0 1 1 1 1 0]
 [3 2 3 3 0 1 1 3 2 2]
 [0 1 1 0 0 0 0 1 3 3]
 [1 0 0 2 3 0 1 3 3 3]
 [3 1 1 3 3 1 2 2 1 2]
 [2 1 3 3 0 0 0 0 0 1]
 [0 3 0 1 0 0 3 1 2 2]
 [3 2 2 3 1 0 2 3 1 2]
 [0 0 0 3 0 3 3 1 0 3]]


Matrix with all the values is 1

In [12]:
matrix_4 = np.ones((2,3))
print(matrix_4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
matrix_5 = np.ones((2,3),dtype=int)
print(matrix_5)

[[1 1 1]
 [1 1 1]]


In [14]:
matrix_6 = np.zeros((2,4))
print(matrix_6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
matrix_7 = np.zeros((3,5),dtype=int)
print(matrix_7)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


Identity Matrix

In [16]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
identity = np.eye(4,dtype=int)
print(identity)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [18]:
identity = np.eye((3,4),dtype=int)
print(identity)

TypeError: 'tuple' object cannot be interpreted as an integer

Transpose of Matrix

In [19]:
a = np.random.randint(100,size=(2,5))
print(a)
b = np.transpose(a)
print(b)

[[74 87 70 14 54]
 [35 35 25  3 64]]
[[74 35]
 [87 35]
 [70 25]
 [14  3]
 [54 64]]


In [21]:
a = np.random.randint(100,size=(2,5))
b = np.random.randint(10,size=(2,5))
print("a")
print(a)
print("b")
print(b)
sum = a + b
print(sum)

a
[[62 24 18 17 75]
 [13  7 90 80 50]]
b
[[4 1 1 4 0]
 [5 3 8 9 6]]
[[66 25 19 21 75]
 [18 10 98 89 56]]


In [22]:
a = np.random.randint(100,size=(2,5))
b = np.random.randint(10,size=(2,5))
print("a")
print(a)
print("b")
print(b)
sum = a - b
print("diff")
print(sum)

a
[[74 40 95 46 66]
 [11 10 28 43 76]]
b
[[5 5 5 7 4]
 [4 6 8 7 9]]
diff
[[69 35 90 39 62]
 [ 7  4 20 36 67]]


In [24]:
a = np.random.randint(100,size=(2,5))
b = np.random.randint(10,size=(2,5))
print("a")
print(a)
print("b")
print(b)
sum = a * b
print("mul")
print(sum)

a
[[58 86  0 81 90]
 [59  6 69 11 87]]
b
[[2 9 7 2 0]
 [1 0 4 1 7]]
mul
[[116 774   0 162   0]
 [ 59   0 276  11 609]]
